### ISSUE TITLE
CRAN archival

### ISSUE THREAD

**Issue by fkohrt** [xoopR/param6#20]
As of 2022-08-26, [param6's CRAN page](https://cran.r-project.org/package=param6) says

> Archived on 2022-08-20 at the maintainer's request.

Does this mean that {param6} is not maintained anymore or was there a different reason for this request?

**Comment by RaphaelS1** [comment]
It's still maintained. See [here](https://twitter.com/RaphaelS101/status/1506321623250571265) for why it's not on CRAN. I'll add installation instructions to the README now

**Comment by fkohrt** [comment]
Thank you for clarifying! I was aware of the deeply lacking acknowledgement and support for RSEs, and your description of CRAN's response to fixing bugs responding to changes in dependencies makes me worry even more. Thanks a lot for continued support and development time!
